version: 2
jobs:
  clang:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run: make configure-clang6-1404
      - run: make configure-pip310
      - run: make configure-cmake
      - run: sudo python3.10 -m pip install mama
      - run: sudo apt -y --allow-unauthenticated install libdw-dev gdb
      - run: mama build clang
      - run: mama test="--verbosity=2"
workflows:
  version: 2
  build_all:
    jobs:
      - clang
