version: 2
orbs:
  win: circleci/windows@5.0 # VS2022

jobs:
  clang:
    description: Ubuntu Clang x64 Build
    resource_class: medium+ # medium+: 3 CPU-s, 6GB RAM, large: 4 CPU-s, 8GB RAM
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt -y --allow-unauthenticated install libdw-dev libunwind-dev gdb
      - run: pipenv install mama
      - run: sudo apt-get install clang-12 libc++-12-dev libc++abi-12-dev -y
      - run: make configure-cmake
      - run: pipenv run mama clang verbose build
      - run: pipenv run mama clang verbose test="--verbosity=2"
  gcc:
    description: Ubuntu GCC x64 Build
    resource_class: medium+ # medium+: 3 CPU-s, 6GB RAM, large: 4 CPU-s, 8GB RAM
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt -y --allow-unauthenticated install libdw-dev libunwind-dev gdb
      - run: pipenv install mama
      - run: sudo apt-get install gcc-11 -y
      - run: make configure-cmake
      - run: pipenv run mama gcc verbose build
      - run: pipenv run mama gcc verbose test="--verbosity=2"
  msvc:
    description: Windows MSVC VS2022 x64 Build
    executor:
      name: win/default
      size: medium # can be medium, large, xlarge, 2xlarge
    steps:
      - checkout
      - run: pip3 install mama
      - run: mama windows verbose build
      - run: mama windows verbose test="--verbosity=2"
workflows:
  version: 2
  build_all:
    jobs:
      - clang
      - gcc
      - msvc
